### ISSUE TITLE
This example does not provide with error handling from backend. Is it possible to do so?

### ISSUE THREAD

**Issue by nakshatrasinghh** [AleksanderZverev/redux-template#1]

**Comment by AleksanderZverev** [comment]
Yes, it's handnling [here](https://github.com/AleksanderZverev/redux-template/blob/main/src/hoc/withQueryResolver.tsx#L72).
You also can handle an error in axios [use midleware](https://github.com/AleksanderZverev/redux-template/blob/main/src/redux/axiosInstance.ts#L12).

**Comment by nakshatrasinghh** [comment]
Here is my backend error response 
{
    "error": true,
    "status": 403,
    "message": "OTP unable to go"
}

How can I use error property from [_,{isError, error}] = useGetOTPMutation()

When I do error.message (it says message does not exist on type error)
